export const quizData = [
  { question: "What executes Java bytecode?", options: ["The text editor", "The JVM", "The operating system shell only", "The Scanner class"], correctIndex: 1, explanation: "The Java compiler produces bytecode, and the Java Virtual Machine executes it." },
  { question: "What is stored by `double answer = 9 / 2;`?", options: ["4.0", "4.5", "5.0", "A compilation error"], correctIndex: 0, explanation: "Both operands are integers, so integer division produces 4 before widening it to 4.0." },
  { question: "What is the result of `(int) 8.99`?", options: ["8", "9", "8.99", "A runtime exception"], correctIndex: 0, explanation: "Narrowing to int discards the fractional part rather than rounding." },
  { question: "Which conversion normally happens automatically?", options: ["double to int", "long to short", "int to double", "String to int"], correctIndex: 2, explanation: "Converting int to double is a widening conversion." },
  { question: "Where can a variable declared inside an if block be used?", options: ["Anywhere in the class", "Only inside that block and its nested blocks", "Only after the block", "In every method"], correctIndex: 1, explanation: "A local variable is limited to its declaring block." },
  { question: "Which expression compares the contents of strings `a` and `b`?", options: ["a == b", "a = b", "a.equals(b)", "a.compare(b)"], correctIndex: 2, explanation: ".equals() compares String content; == compares references." },
  { question: "Without braces, how many statements belong to an if?", options: ["Every indented statement", "Exactly one following statement", "Every statement until else", "None"], correctIndex: 1, explanation: "Java ignores indentation when determining block structure." },
  { question: "What is the last valid index of an array with length 12?", options: ["10", "11", "12", "13"], correctIndex: 1, explanation: "Java arrays are zero-indexed, so the last index is length - 1." },
  { question: "Which loop guarantees that its body runs at least once?", options: ["for", "while", "do-while", "enhanced for"], correctIndex: 2, explanation: "A do-while loop checks its condition after executing the body." },
  { question: "Which loop is usually clearest for exactly 100 repetitions?", options: ["for", "while", "do-while", "try-catch"], correctIndex: 0, explanation: "A for loop keeps initialization, condition, and update together for count-controlled repetition." },
];
