export const quizData = [
  { question: "Which Scanner method reads a complete line including spaces?", options: ["next()", "nextLine()", "nextInt()", "hasNext()"], correctIndex: 1, explanation: "nextLine() reads up to the line ending rather than stopping at the first space." },
  { question: "Why can nextLine() appear to be skipped after nextInt()?", options: ["nextLine() is broken", "The integer is too large", "nextInt() leaves the line ending in the buffer", "Scanner closes automatically"], correctIndex: 2, explanation: "The next nextLine() consumes the unconsumed end of the current line." },
  { question: "What should happen after hasNextInt() returns false during validation?", options: ["Read with nextInt() anyway", "Consume the invalid token", "Close the program", "Return zero silently"], correctIndex: 1, explanation: "The invalid token must be consumed or the loop will inspect the same token forever." },
  { question: "What does a void method return?", options: ["0", "null", "No value", "false"], correctIndex: 2, explanation: "void indicates that the method does not return a value." },
  { question: "In `square(5)`, what is 5?", options: ["A parameter", "An argument", "A return type", "A method signature"], correctIndex: 1, explanation: "An argument is the actual value supplied to a method call." },
  { question: "Which declaration correctly describes a method returning true or false?", options: ["void isValid()", "boolean isValid()", "String isValid()", "return isValid()"], correctIndex: 1, explanation: "The boolean return type promises a true or false result." },
  { question: "Why use files instead of ordinary local variables for saved scores?", options: ["Files are always faster", "Files persist after the program exits", "Variables cannot hold numbers", "Files need no error handling"], correctIndex: 1, explanation: "Local in-memory values disappear when the program stops, while files provide persistence." },
  { question: "What is a key benefit of try-with-resources?", options: ["It prevents all exceptions", "It automatically closes declared resources", "It converts text to integers", "It makes files permanent"], correctIndex: 1, explanation: "Readers, writers, scanners, and similar resources are closed automatically." },
  { question: "Which exception commonly represents a file input/output failure?", options: ["ArithmeticException", "IOException", "ClassCastException", "IndexOutOfBoundsException"], correctIndex: 1, explanation: "IOException is the standard checked exception family for I/O failures." },
  { question: "When reading lines, what normally signals the end of a file?", options: ["An empty string", "The number -1 in every API", "A null result from readLine()", "A space character"], correctIndex: 2, explanation: "BufferedReader.readLine() returns null when no more lines remain." },
];
