export const quizData = [
  { question: "Time and space complexity of Floyd's Cycle Detection?", options: ["$O(n)$ / $O(n)$", "$O(n \\log n)$ / $O(1)$", "$O(n)$ / $O(1)$", "$O(1)$ / $O(1)$"], correctIndex: 2, explanation: "It visits nodes linearly and only uses two pointers." },
  { question: "Time complexity to delete a node in a DLL if you have the reference?", options: ["$O(1)$", "$O(\\log n)$", "$O(n)$", "$O(n^2)$"], correctIndex: 0, explanation: "You just update the prev and next pointers of its neighbors." },
  { question: "Space complexity of iterative Linked List reversal?", options: ["$O(1)$", "$O(\\log n)$", "$O(n)$", "$O(n^2)$"], correctIndex: 0, explanation: "It only requires three pointers (prev, curr, next)." },
  { question: "In the 'Find Middle' algorithm, the fast pointer moves at?", options: ["Half the speed of slow", "The same speed as slow", "Twice the speed of slow", "Three times the speed of slow"], correctIndex: 2, explanation: "When fast reaches the end, slow will be exactly in the middle." },
  { question: "Time complexity to delete the tail node in a Singly Linked List?", options: ["$O(1)$", "$O(\\log n)$", "$O(n)$", "$O(n^2)$"], correctIndex: 2, explanation: "You must traverse to the second-to-last node to update its next pointer." },
  { question: "In a Circular Linked List, the last node's next pointer points to?", options: ["null", "The middle node", "The head node", "Itself"], correctIndex: 2, explanation: "It creates a continuous loop by pointing back to the start." },
  { question: "Which linked list variant is used to implement an LRU Cache?", options: ["Singly Linked List", "Circular Linked List", "Doubly Linked List", "Skip List"], correctIndex: 2, explanation: "DLL allows $O(1)$ removal of arbitrary nodes (the least recently used)." },
  { question: "Memory overhead of a DLL compared to an SLL?", options: ["None", "One extra pointer per node", "Two extra pointers per node", "It uses less memory"], correctIndex: 1, explanation: "Each node requires an additional 'prev' pointer." },
  { question: "After detecting a cycle with Floyd's, how do you find the start?", options: ["Reset fast to head, move both 2x", "Reset slow to head, move both 1x", "Reset fast to slow, move both 1x", "Traverse from head counting nodes"], correctIndex: 1, explanation: "The distance from head to cycle start equals the distance from the meeting point to the start." },
  { question: "Time complexity to insert at the head of an SLL?", options: ["$O(1)$", "$O(\\log n)$", "$O(n)$", "$O(n^2)$"], correctIndex: 0, explanation: "You just create a node and point it to the old head." },
  { question: "Time complexity to merge two sorted linked lists of sizes $n$ and $m$?", options: ["$O(n)$", "$O(m)$", "$O(n+m)$", "$O(n \\cdot m)$"], correctIndex: 2, explanation: "You traverse each node exactly once." },
  { question: "Optimal way to find the intersection of two Y-shaped lists?", options: ["Use a HashMap", "Nested loops", "Find length difference, advance the longer list, then traverse together", "Reverse both lists"], correctIndex: 2, explanation: "This aligns the pointers to reach the intersection at the exact same time." },
  { question: "Optimal space complexity to check if a Linked List is a palindrome?", options: ["$O(n)$ Stack", "$O(n)$ Array", "$O(1)$ by reversing the second half", "$O(\\log n)$ Recursion"], correctIndex: 2, explanation: "Find middle, reverse second half, compare, then optionally restore." },
  { question: "Best practice when swapping adjacent nodes in pairs?", options: ["Swap values directly", "Use a Dummy Head node", "Use recursion only", "Convert to array first"], correctIndex: 1, explanation: "A dummy head simplifies edge cases, especially swapping the first pair." },
  { question: "How to flatten a multilevel doubly linked list?", options: ["Use a Queue", "Use DFS/BFS with a stack or recursion", "Sort the nodes", "It cannot be flattened"], correctIndex: 1, explanation: "You traverse the main list, and when a child exists, you recursively flatten it." }
];