export const quizData = [
  { question: "To compute a GPA using only 'CSI' courses from a linked list of students, what is the most efficient filtering logic?", options: ["Sort the list alphabetically, then binary search for 'CSI'", "Traverse once, checking if `course.startsWith('CSI')` and accumulating weights", "Copy all courses to an array, then filter", "Use a HashMap to group courses by prefix"], correctIndex: 1, explanation: "A single $\\mathcal{O}(N)$ traversal with conditional accumulation requires $\\mathcal{O}(1)$ auxiliary space and avoids the overhead of sorting or hashing." },
  { question: "In the GPA formula $\\frac{\\sum (credit \\times grade)}{n}$, what does $n$ represent?", options: ["Total number of students", "Total number of courses taken", "Sum of all credits", "Number of 'CSI' courses"], correctIndex: 2, explanation: "In a weighted GPA, the denominator must be the sum of the credits (weights), not just the raw count of courses." },
  { question: "What is the time complexity to find the intersection of two Y-shaped singly linked lists?", options: ["$\\mathcal{O}(N \\cdot M)$", "$\\mathcal{O}(N + M)$", "$\\mathcal{O}(\\log N)$", "$\\mathcal{O}(1)$"], correctIndex: 1, explanation: "By calculating the length difference and advancing the longer list's pointer, both pointers traverse the remaining shared path in $\\mathcal{O}(N + M)$ time." },
  { question: "When reversing a singly linked list iteratively, how many pointers are strictly required?", options: ["1", "2", "3", "4"], correctIndex: 2, explanation: "You need `prev`, `curr`, and `next` to safely reverse the `next` pointer without losing the rest of the list." },
  { question: "What is the main advantage of a Dummy Head node in linked list operations?", options: ["It reduces memory usage", "It eliminates edge cases when modifying the actual head", "It makes the list circular", "It speeds up traversal"], correctIndex: 1, explanation: "A dummy head ensures the list is never truly 'empty' from a pointer perspective, simplifying insertions/deletions at index 0." },
  { question: "In Floyd's Cycle Detection, if the slow pointer moves 1 step and fast moves 2 steps, where do they meet?", options: ["At the head of the list", "At the exact start of the cycle", "Inside the cycle", "At the tail node"], correctIndex: 2, explanation: "The fast pointer will eventually lap the slow pointer inside the cycle. To find the start, reset one pointer to head and move both 1 step." },
  { question: "What is the space complexity of an iterative linked list reversal?", options: ["$\\mathcal{O}(N)$", "$\\mathcal{O}(\\log N)$", "$\\mathcal{O}(1)$", "$\\mathcal{O}(N^2)$"], correctIndex: 2, explanation: "It only uses three pointers (`prev`, `curr`, `next`), requiring constant auxiliary space." },
  { question: "To delete a node in a Doubly Linked List given its reference, what is the time complexity?", options: ["$\\mathcal{O}(1)$", "$\\mathcal{O}(\\log N)$", "$\\mathcal{O}(N)$", "$\\mathcal{O}(N^2)$"], correctIndex: 0, explanation: "Because you have the `prev` and `next` pointers directly on the node, you can bypass it in constant time without searching." },
  { question: "If a linked list represents a polynomial, how should nodes be ordered for efficient addition?", options: ["By coefficient descending", "By exponent ascending/descending", "Randomly", "By memory address"], correctIndex: 1, explanation: "Ordering by exponent allows a single simultaneous traversal (merge-like) to add terms with matching exponents." },
  { question: "What happens if you forget to update the `tail` pointer when appending to a singly linked list?", options: ["The list becomes circular", "Subsequent appends take $\\mathcal{O}(N)$ instead of $\\mathcal{O}(1)$", "A StackOverflow occurs", "The head pointer is lost"], correctIndex: 1, explanation: "Without a maintained tail, you must traverse from the head to find the end for every insertion, degrading performance to $\\mathcal{O}(N)$." }
];