export const quizData = [
  { question: "Convert the infix expression $A + B * C / F$ to postfix using a stack.", options: ["A B C * F / +", "A B + C * F /", "A B C * + F /", "A B C F / * +"], correctIndex: 0, explanation: "Multiplication and division have higher precedence. B * C is grouped, then divided by F, and finally added to A." },
  { question: "In an array-based Stack, what is the correct implementation of `IsFull()`?", options: ["top == 0", "top == capacity", "top == capacity - 1", "size == capacity / 2"], correctIndex: 2, explanation: "Assuming a 0-indexed array, the maximum valid index is `capacity - 1`." },
  { question: "What is the primary use case for a Monotonic Stack?", options: ["Sorting arrays", "Finding the Next Greater/Smaller Element in $\\mathcal{O}(N)$", "Implementing recursion", "Breadth-First Search"], correctIndex: 1, explanation: "By maintaining elements in strictly increasing/decreasing order, it efficiently solves range and boundary problems." },
  { question: "When evaluating a postfix expression, what happens when an operator is encountered?", options: ["Push it to the stack", "Pop one operand and apply", "Pop two operands, apply, and push result", "Clear the stack"], correctIndex: 2, explanation: "Postfix evaluation requires two operands for any binary operator. You pop the top two, compute, and push the result back." },
  { question: "What condition defines an Empty Stack in an array implementation?", options: ["top == 0", "top == -1", "top == capacity", "size == 1"], correctIndex: 1, explanation: "If `top` starts at -1, it indicates no elements are present. Popping at this state causes an Underflow." },
  { question: "Why does a Circular Queue sacrifice one array slot?", options: ["To store the size variable", "To distinguish between the Full and Empty states", "To prevent integer overflow", "To store the tail pointer"], correctIndex: 1, explanation: "If `front == rear` means empty, then a completely full queue would also result in `front == rear` after wrapping. Sacrificing one slot prevents this ambiguity." },
  { question: "What data structure is used to check for balanced parentheses?", options: ["Queue", "Stack", "Deque", "Priority Queue"], correctIndex: 1, explanation: "Opening brackets are pushed. Closing brackets pop the stack and verify a match. LIFO behavior perfectly mirrors nesting." },
  { question: "In the Shunting Yard algorithm, when is an operator popped from the stack to the output?", options: ["When a higher precedence operator is read", "When a lower or equal precedence operator is read", "Only at the end of the expression", "When an operand is read"], correctIndex: 1, explanation: "Operators are popped if the incoming operator has lower or equal precedence (for left-associative operators)." },
  { question: "What is the time complexity of finding the maximum in a sliding window using a Monotonic Deque?", options: ["$\\mathcal{O}(N \\log K)$", "$\\mathcal{O}(N \\cdot K)$", "$\\mathcal{O}(N)$", "$\\mathcal{O}(N^2)$"], correctIndex: 2, explanation: "Each element is added and removed from the deque at most once, resulting in linear time overall." },
  { question: "If a string is randomly exchanged $x$ times (where $x = length/2$), what is the time complexity?", options: ["$\\mathcal{O}(1)$", "$\\mathcal{O}(\\log N)$", "$\\mathcal{O}(N)$", "$\\mathcal{O}(N^2)$"], correctIndex: 2, explanation: "Converting to `char[]` takes $\\mathcal{O}(N)$. Performing $N/2$ swaps takes $\\mathcal{O}(N)$. Reconstructing the String takes $\\mathcal{O}(N)$. Total is $\\mathcal{O}(N)$." }
];