export const quizData = [
  { question: "What is the closed-form formula for $\sum_{i=1}^n i$?", options: ["$\frac{n(n-1)}{2}$", "$\frac{n(n+1)}{2}$", "$\frac{n(n+1)(2n+1)}{6}$", "$n^2$"], correctIndex: 1, explanation: "The sum of the first $n$ integers is $\frac{n(n+1)}{2}$." },
  { question: "Translate: `for i=1 to n: for j=i to n: O(1)`", options: ["$\sum_{i=1}^n \sum_{j=1}^i 1$", "$\sum_{i=1}^n \sum_{j=i}^n 1$", "$\sum_{j=1}^n \sum_{i=1}^j 1$", "$\sum_{i=1}^n \sum_{j=1}^n 1$"], correctIndex: 1, explanation: "The outer loop runs $i$ from 1 to $n$, and the inner loop runs $j$ from $i$ to $n$." },
  { question: "What is the complexity of $\sum_{i=1}^n \sum_{j=1}^i 1$?", options: ["$\Theta(n)$", "$\Theta(n \log n)$", "$\Theta(n^2)$", "$\Theta(n^3)$"], correctIndex: 2, explanation: "The inner sum is $i$. The outer sum is $\sum i = \frac{n(n+1)}{2} = \Theta(n^2)$." },
  { question: "What is the closed-form formula for $\sum_{i=1}^n i^2$?", options: ["$\frac{n(n+1)}{2}$", "$\frac{n(n+1)(2n+1)}{6}$", "$(\frac{n(n+1)}{2})^2$", "$\frac{n^3}{3}$"], correctIndex: 1, explanation: "The sum of squares is $\frac{n(n+1)(2n+1)}{6}$, which is $\Theta(n^3)$." },
  { question: "Analyze: `for i=1 to n: for j=1 to n step i: O(1)`", options: ["$\Theta(n)$", "$\Theta(n \log n)$", "$\Theta(n^2)$", "$\Theta(n \sqrt{n})$"], correctIndex: 1, explanation: "The inner loop runs $n/i$ times. Total is $n \sum (1/i) = n H_n = \Theta(n \log n)$." },
  { question: "What is the value of $\sum_{i=0}^n r^i$ for $r > 1$?", options: ["$\frac{r^{n+1} - 1}{r - 1}$", "$\frac{1 - r^{n+1}}{1 - r}$", "$\frac{r^n - 1}{r - 1}$", "$\infty$"], correctIndex: 0, explanation: "The standard formula for a finite geometric series starting at $i=0$." },
  { question: "If `for i=1 to n: for j=1 to i^2: O(1)`, what is the complexity?", options: ["$\Theta(n^2)$", "$\Theta(n^3)$", "$\Theta(n^4)$", "$\Theta(n^2 \log n)$"], correctIndex: 1, explanation: "Total iterations are $\sum_{i=1}^n i^2 = \Theta(n^3)$." },
  { question: "What is the asymptotic bound of the Harmonic series $H_n$?", options: ["$\Theta(1)$", "$\Theta(\log n)$", "$\Theta(n)$", "$\Theta(n \log n)$"], correctIndex: 1, explanation: "$H_n \approx \ln n + \gamma$, so it is $\Theta(\log n)$." },
  { question: "Translate: `for i=n down to 1: for j=1 to i: O(1)`", options: ["$\sum_{i=1}^n \sum_{j=1}^i 1$", "$\sum_{i=n}^1 \sum_{j=1}^i 1$", "$\sum_{i=1}^n \sum_{j=i}^n 1$", "$\sum_{i=1}^n i$"], correctIndex: 0, explanation: "Reversing the loop direction doesn't change the set of values $i$ takes." },
  { question: "What is $\sum_{i=1}^n c$ where $c$ is a constant?", options: ["$c$", "$c \cdot n$", "$c \cdot n^2$", "$\frac{c(c+1)}{2}$"], correctIndex: 1, explanation: "Adding a constant $n$ times yields $c \cdot n$." },
  { question: "Which identity simplifies $\sum (a_i + b_i)$?", options: ["Cannot be simplified", "$\sum a_i + \sum b_i$", "$(\sum a_i) \cdot (\sum b_i)$", "$\sum (a_i \cdot b_i)$"], correctIndex: 1, explanation: "Summation is a linear operator." },
  { question: "Complexity of `while n > 1: n = n / 2`?", options: ["$\Theta(1)$", "$\Theta(\log n)$", "$\Theta(n)$", "$\Theta(\sqrt{n})$"], correctIndex: 1, explanation: "Halving the input size yields $\log_2 n$ iterations." },
  { question: "What is $\sum_{i=1}^n (2i - 1)$?", options: ["$n^2$", "$n(n+1)$", "$\frac{n(n+1)}{2}$", "$2n^2$"], correctIndex: 0, explanation: "The sum of the first $n$ odd numbers is exactly $n^2$." },
  { question: "Max iterations: `for i=1 to n: for j=1 to i^2: for k=1 to j: O(1)`?", options: ["$\Theta(n^3)$", "$\Theta(n^4)$", "$\Theta(n^5)$", "$\Theta(n^6)$"], correctIndex: 2, explanation: "Inner is $j$. Middle is $\sum j = \Theta(i^4)$. Outer is $\sum i^4 = \Theta(n^5)$." },
  { question: "Why drop lower-order terms in asymptotic analysis?", options: ["They don't affect exact count", "As $n \to \infty$, the highest-degree term dominates growth", "Lower-order terms are negative", "Compiler optimizes them"], correctIndex: 1, explanation: "The highest-degree term grows significantly faster, making lower terms negligible." }
];