export const quizData = [
  { question: "In $T(n) = aT(n/b) + f(n)$, what is $a$?", options: ["Cost of dividing", "Number of subproblems", "Subproblem size", "Base case"], correctIndex: 1, explanation: "$a$ is the number of recursive calls made at each step." },
  { question: "For $T(n) = 2T(n/2) + n$, what is $c_{crit}$?", options: ["$0$", "$1$", "$2$", "$\log_2 n$"], correctIndex: 1, explanation: "$c_{crit} = \log_b a = \log_2 2 = 1$." },
  { question: "Which Master Theorem case applies to $T(n) = 2T(n/2) + n$?", options: ["Case 1", "Case 2", "Case 3", "Does not apply"], correctIndex: 1, explanation: "$f(n) = n = \Theta(n^{c_{crit}})$, which is exactly Case 2." },
  { question: "Solution to $T(n) = 2T(n/2) + n$?", options: ["$\Theta(n)$", "$\Theta(n \log n)$", "$\Theta(n^2)$", "$\Theta(\log n)$"], correctIndex: 1, explanation: "Case 2 yields $\Theta(n^{c_{crit}} \log n) = \Theta(n \log n)$." },
  { question: "For $T(n) = 3T(n/4) + n \log n$, what is $c_{crit}$?", options: ["$\log_3 4$", "$\log_4 3$", "$1$", "$\log_3 n$"], correctIndex: 1, explanation: "$c_{crit} = \log_b a = \log_4 3$." },
  { question: "What is the regularity condition for Case 3?", options: ["$f(n)$ is polynomial", "$a f(n/b) \le k f(n)$ for $k < 1$", "$f(n)$ is decreasing", "$a > b$"], correctIndex: 1, explanation: "It ensures the root's work dominates the total work of all subproblems." },
  { question: "Goal of the Iteration Method?", options: ["Find base case", "Identify a pattern to express as a summation", "Convert to differential equation", "Prove Master Theorem"], correctIndex: 1, explanation: "Repeated expansion reveals a pattern that can be summed." },
  { question: "What does a Recursion Tree visually represent?", options: ["Call stack", "Cost of each level of recursion", "Memory allocation", "Base cases"], correctIndex: 1, explanation: "It breaks down the recurrence to sum the costs level by level." },
  { question: "Complexity of $T(n) = T(n/2) + 1$?", options: ["$\Theta(1)$", "$\Theta(\log n)$", "$\Theta(n)$", "$\Theta(n \log n)$"], correctIndex: 1, explanation: "Binary search recurrence. Case 2 applies, yielding $\Theta(\log n)$." },
  { question: "Complexity of $T(n) = 4T(n/2) + n^2$?", options: ["$\Theta(n)$", "$\Theta(n \log n)$", "$\Theta(n^2)$", "$\Theta(n^2 \log n)$"], correctIndex: 3, explanation: "$c_{crit} = 2$. $f(n) = n^2 = \Theta(n^2)$. Case 2 yields $\Theta(n^2 \log n)$." },
  { question: "Complexity of $T(n) = 8T(n/2) + n^2$?", options: ["$\Theta(n^2)$", "$\Theta(n^2 \log n)$", "$\Theta(n^3)$", "$\Theta(n^3 \log n)$"], correctIndex: 2, explanation: "$c_{crit} = 3$. $f(n) = n^2 = O(n^{3-\epsilon})$. Case 1 yields $\Theta(n^3)$." },
  { question: "Why doesn't Master Theorem apply to $T(n) = 2T(n/2) + n \log n$?", options: ["$a$ not integer", "$f(n)$ lacks polynomial factor $n^\epsilon$ for Case 3", "$b \le 1$", "It is Case 2"], correctIndex: 1, explanation: "$n \log n$ is larger than $n$, but not by a polynomial factor $n^\epsilon$." },
  { question: "Standard base case assumption for asymptotic recurrences?", options: ["$T(0) = 0$", "$T(1) = \Theta(1)$", "$T(n) = 0$ for $n < 0$", "$T(1) = n$"], correctIndex: 1, explanation: "The base case is a constant, which doesn't affect the highest-order term." },
  { question: "Complexity of $T(n) = T(n-1) + n$?", options: ["$\Theta(n)$", "$\Theta(n \log n)$", "$\Theta(n^2)$", "$\Theta(2^n)$"], correctIndex: 2, explanation: "Expands to $\sum_{i=1}^n i = \frac{n(n+1)}{2} = \Theta(n^2)$." },
  { question: "Primary advantage of Recursion Tree method?", options: ["More rigorous", "Visual intuition to guess the solution for Substitution method", "Doesn't need base case", "Works for all recurrences"], correctIndex: 1, explanation: "It's a heuristic tool to visualize cost distribution and guess the bound." }
];