export const flashcardData = [
  { front: "Algorithm", back: "A well-defined sequence of instructions that solves a specific problem in a finite amount of time." },
  { front: "Program", back: "An implementation of an algorithm in a programming language." },
  { front: "Algorithm Efficiency", back: "A measure of the time and storage resources an algorithm requires." },
  { front: "Time Complexity", back: "An estimate of how an algorithm's running time grows as input size N grows." },
  { front: "Input Size N", back: "A measure of the amount of input, such as the number of elements in an array." },
  { front: "Why Runtime Changes", back: "Runtime can change with the input data and normally increases as the input size grows." },
  { front: "Experimental Analysis", back: "Implement algorithms, run them on identical datasets, repeat measurements, and compare average clock times." },
  { front: "Experimental Limitation", back: "Measured time depends on hardware, software, coding style, and the particular datasets tested." },
  { front: "Methodological Analysis", back: "Use mathematical counting to express runtime as a function of N without relying on a specific machine." },
  { front: "Primitive Operation", back: "A basic action such as assignment, arithmetic, comparison, array indexing, or a method call." },
  { front: "Primitive Operation Assumption", back: "For introductory analysis, each primitive operation is treated as taking constant time." },
  { front: "T(N)", back: "A function representing the estimated running time for an input of size N." },
  { front: "Best Case", back: "The shortest possible runtime among inputs of size N." },
  { front: "Average Case", back: "The expected runtime across possible inputs of size N; it is often difficult to calculate." },
  { front: "Worst Case", back: "The maximum runtime among inputs of size N and the case most commonly analyzed in this course." },
  { front: "Sequential Statements", back: "Add the runtimes of the individual statements." },
  { front: "If-Else Rule", back: "For a worst-case estimate, count the condition plus the more expensive branch." },
  { front: "Loop Rule", back: "Multiply the cost of the loop body by the number of iterations." },
  { front: "Single Loop over N", back: "Usually O(N) because the body executes N times." },
  { front: "Two N-by-N Nested Loops", back: "Usually O(N^2) because the inner body executes N x N times." },
  { front: "Growth Rate", back: "How quickly an algorithm's running time increases as N increases." },
  { front: "Big-O Notation", back: "Notation used to describe an upper growth-rate category, commonly the worst-case growth in this course." },
  { front: "Dominant Term", back: "The fastest-growing term in a runtime expression; it determines the Big-O category." },
  { front: "Big-O Simplification", back: "Keep the dominant term and drop coefficients, constants, and lower-order terms." },
  { front: "O(1)", back: "Constant growth: the amount of work does not grow with N." },
  { front: "O(log N)", back: "Logarithmic growth: the remaining problem is commonly reduced by a fixed factor each step." },
  { front: "O(N)", back: "Linear growth: doubling the input roughly doubles the work." },
  { front: "O(N log N)", back: "Linearithmic growth, common in efficient divide-and-conquer sorting algorithms." },
  { front: "O(N^2)", back: "Quadratic growth, often produced by two nested loops over N items." },
  { front: "O(N^3)", back: "Cubic growth, often produced by three nested loops over N items." },
  { front: "O(2^N)", back: "Exponential growth, where a small increase in N can cause a very large increase in work." },
  { front: "Growth Order", back: "O(1) < O(log N) < O(N) < O(N log N) < O(N^2) < O(N^3) < O(2^N) < O(N!)." },
];
