export const quizData = [
  {
    question: "What is the primary function of GHC?",
    options: [
      "The Glasgow Haskell Interpreter, used for debugging.",
      "The Glasgow Haskell Compiler, used to compile Haskell source code.",
      "The Graphical Haskell Console, used for UI design.",
      "The Generic Heuristic Compiler, used for AI."
    ],
    correctIndex: 1,
    explanation: "GHC stands for the Glasgow Haskell Compiler, the standard compiler for Haskell."
  },
  {
    question: "What is GHCi?",
    options: [
      "A batch compiler for production environments.",
      "The interactive Read-Eval-Print Loop (REPL) for Haskell.",
      "A graphical user interface for Haskell.",
      "A static analysis tool for type checking."
    ],
    correctIndex: 1,
    explanation: "GHCi is the interactive Read-Eval-Print Loop (REPL) used for testing expressions and loading modules."
  },
  {
    question: "What is the 'Layout Rule' in Haskell?",
    options: [
      "The rule that dictates how memory is allocated.",
      "The rule that uses indentation to define code blocks.",
      "The rule that requires all functions to be laid out horizontally.",
      "The rule that prohibits the use of parentheses."
    ],
    correctIndex: 1,
    explanation: "The Layout Rule (or offside rule) uses indentation to define code blocks, replacing the need for braces in many contexts."
  },
  {
    question: "What is the strict prohibition regarding whitespace in Haskell?",
    options: [
      "Using more than 4 spaces for indentation.",
      "Mixing tabs and spaces in the same file.",
      "Using whitespace inside function names.",
      "Placing whitespace at the end of a line."
    ],
    correctIndex: 1,
    explanation: "You must never mix tabs and spaces in a Haskell file, as it will cause the compiler to throw a parse error."
  },
  {
    question: "In Haskell's case sensitivity rules, what must start with an uppercase letter?",
    options: [
      "Functions and variables",
      "Types, Typeclasses, and Data Constructors",
      "Module names only",
      "Comments"
    ],
    correctIndex: 1,
    explanation: "Types, Typeclasses, and Data Constructors must start with an uppercase letter."
  },
  {
    question: "In Haskell's case sensitivity rules, what must start with a lowercase letter?",
    options: [
      "Data Constructors",
      "Typeclasses",
      "Functions, variables, and parameters",
      "Module names"
    ],
    correctIndex: 2,
    explanation: "Functions, variables, and parameters must start with a lowercase letter."
  },
  {
    question: "What is the syntax for a single-line comment in Haskell?",
    options: [
      "//",
      "#",
      "--",
      "/*"
    ],
    correctIndex: 2,
    explanation: "Single-line comments in Haskell start with `--`."
  },
  {
    question: "What is the syntax for a multi-line comment in Haskell?",
    options: [
      "/* and */",
      "<!-- and -->",
      "{- and -}",
      "#< and >#"
    ],
    correctIndex: 2,
    explanation: "Multi-line comments in Haskell are enclosed in `{-` and `-}`."
  },
  {
    question: "Which GHCi command is used to load a Haskell script?",
    options: [
      ":run",
      ":load or :l",
      ":start",
      ":open"
    ],
    correctIndex: 1,
    explanation: "The `:load` or `:l` command is used to load a Haskell script into the GHCi REPL."
  },
  {
    question: "Which GHCi command is used to reload the currently loaded modules?",
    options: [
      ":refresh",
      ":update",
      ":reload or :r",
      ":restart"
    ],
    correctIndex: 2,
    explanation: "The `:reload` or `:r` command reloads the currently loaded modules after changes have been made."
  },
  {
    question: "Which GHCi command prints the type of an expression without evaluating it?",
    options: [
      ":print",
      ":type or :t",
      ":check",
      ":signature"
    ],
    correctIndex: 1,
    explanation: "The `:type` or `:t` command prints the type signature of an expression."
  },
  {
    question: "Which GHCi command exits the interactive session?",
    options: [
      ":exit",
      ":stop",
      ":quit or :q",
      ":end"
    ],
    correctIndex: 2,
    explanation: "The `:quit` or `:q` command exits the GHCi session."
  },
  {
    question: "What is the command to compile a Haskell file `myFile.hs` into an executable `myProgram`?",
    options: [
      "ghc myFile.hs -o myProgram",
      "ghc -o myProgram myFile.hs",
      "haskell compile myFile.hs myProgram",
      "runhaskell myFile.hs > myProgram"
    ],
    correctIndex: 1,
    explanation: "The correct syntax is `ghc -o myProgram myFile.hs`, where `-o` specifies the output executable name."
  },
  {
    question: "What is the purpose of the `.hi` file generated by GHC?",
    options: [
      "It is the high-level intermediate representation.",
      "It is the Haskell interface file containing type information for other modules.",
      "It is the hidden initialization script.",
      "It is the hardware instruction set."
    ],
    correctIndex: 1,
    explanation: "The `.hi` file is the Haskell interface file, which contains type information needed when compiling other modules that import this one."
  },
  {
    question: "What is the purpose of the `.o` file generated by GHC?",
    options: [
      "It is the output log file.",
      "It is the compiled object file containing machine code.",
      "It is the optimization profile.",
      "It is the original source code backup."
    ],
    correctIndex: 1,
    explanation: "The `.o` file is the compiled object file containing the native machine code."
  }
];