export const quizData = [
  { question: "In Java 8+, a HashMap bucket converts to a Red-Black Tree when it exceeds how many nodes?", options: ["4 nodes", "8 nodes", "16 nodes", "32 nodes"], correctIndex: 1, explanation: "Treeification happens at 8 to prevent O(N) worst-case lookups in heavily collided buckets." },
  { question: "What is the formula for the Load Factor of a hash table?", options: ["capacity / size", "size / capacity", "size / buckets", "collisions / size"], correctIndex: 1, explanation: "It measures how full the table is (number of entries divided by number of buckets)." },
  { question: "What is the worst-case time complexity of Separate Chaining if all keys hash to the same bucket?", options: ["O(1)", "O(log N)", "O(N)", "O(N^2)"], correctIndex: 2, explanation: "If all keys hash to the same bucket, it degrades into a single linked list traversal." },
  { question: "Linear probing suffers primarily from which issue?", options: ["Secondary clustering", "Primary clustering", "Infinite loops", "Memory fragmentation"], correctIndex: 1, explanation: "Contiguous blocks of occupied slots form, slowing down insertions and searches." },
  { question: "Double hashing is designed to avoid:", options: ["Collisions entirely", "Primary and secondary clustering", "Rehashing", "Memory leaks"], correctIndex: 1, explanation: "Using a second hash function for the step size eliminates both types of clustering." },
  { question: "A Bloom Filter can produce which type of error?", options: ["False negatives", "False positives", "Both false positives and negatives", "No errors possible"], correctIndex: 1, explanation: "It can say an item 'might' exist (false positive), but never 'definitely doesn't' if it does." },
  { question: "What happens if you override equals() but NOT hashCode() in Java?", options: ["Compilation error", "Runtime error", "HashMaps will fail to find objects correctly", "Nothing"], correctIndex: 2, explanation: "Equal objects will have different hash codes, breaking HashMap/HashSet contracts." },
  { question: "What is the time complexity of Rehashing all elements in a table?", options: ["O(1)", "O(log N)", "O(N)", "O(N^2)"], correctIndex: 2, explanation: "Every existing element must be re-inserted into the new larger table." },
  { question: "Using a mutable object as a HashMap key causes:", options: ["Faster lookups", "The entry to be lost", "Automatic rehashing", "ConcurrentModificationException"], correctIndex: 1, explanation: "If the key's hash changes after insertion, you can never find the bucket again." },
  { question: "What is the purpose of a Tombstone in Open Addressing?", options: ["To mark the end of the table", "To indicate a deleted slot without breaking probe sequences", "To store overflow data", "To encrypt the hash"], correctIndex: 1, explanation: "If you just leave a null, searches for elements further down the probe sequence will terminate early." }
];