export const quizData = [
  { question: "If $f(n) = 3n^2 + 5n + 2$, what is the tight bound?", options: ["$O(n)$", "$\\Theta(n^2)$", "$\\Omega(n^3)$", "$o(n^2)$"], correctIndex: 1, explanation: "The highest order term dominates, making it $\\Theta(n^2)$." },
  { question: "Which notation indicates a strict upper bound?", options: ["Big-O", "Big-Omega", "Little-o", "Big-Theta"], correctIndex: 2, explanation: "Little-o ($o$) means $f(n)$ grows strictly slower than $g(n)$." },
  { question: "Amortized cost of ArrayList add?", options: ["$O(1)$", "$O(\\log n)$", "$O(n)$", "$O(n^2)$"], correctIndex: 0, explanation: "Resizing is rare, averaging to $O(1)$ per operation." },
  { question: "Worst-case time of a single ArrayList add?", options: ["$O(1)$", "$O(\\log n)$", "$O(n)$", "$O(n^2)$"], correctIndex: 2, explanation: "Triggering a resize requires copying all $n$ elements." },
  { question: "Master theorem: $T(n)=8T(n/2)+n^2$?", options: ["$O(n^2)$", "$O(n^2 \\log n)$", "$O(n^3)$", "$O(n^3 \\log n)$"], correctIndex: 2, explanation: "$n^{\\log_2 8} = n^3$. $f(n)$ is smaller, so Case 1 applies." },
  { question: "If P=NP, what fundamentally breaks?", options: ["Sorting algorithms", "Modern Cryptography", "Binary Search", "Graph Traversal"], correctIndex: 1, explanation: "Public-key crypto relies on problems being hard to solve." },
  { question: "The Halting Problem was proved undecidable by?", options: ["Alonzo Church", "Alan Turing", "Kurt Gödel", "John von Neumann"], correctIndex: 1, explanation: "Alan Turing proved no general algorithm can exist." },
  { question: "Space complexity of recursive binary search?", options: ["$O(1)$", "$O(\\log n)$", "$O(n)$", "$O(n \\log n)$"], correctIndex: 1, explanation: "The call stack depth reaches $\\log n$." },
  { question: "Time complexity of naive recursive Fibonacci?", options: ["$O(n)$", "$O(n \\log n)$", "$O(n^2)$", "$O(2^n)$"], correctIndex: 3, explanation: "It recalculates overlapping subproblems exponentially." },
  { question: "Aggregate method total cost for $n$ ArrayList inserts?", options: ["$O(1)$", "$O(\\log n)$", "$O(n)$", "$O(n^2)$"], correctIndex: 2, explanation: "Total is $2n-1$, which simplifies to $O(n)$." },
  { question: "Standard potential method $\\Phi(D)$ for ArrayList?", options: ["$size$", "$capacity$", "$2 \\cdot size - capacity$", "$size - capacity$"], correctIndex: 2, explanation: "This function perfectly captures the 'debt' of resizing." },
  { question: "Which algorithm is $O(n \\log n)$ on average?", options: ["Quick Sort", "Bubble Sort", "Insertion Sort", "Selection Sort"], correctIndex: 0, explanation: "QuickSort averages $O(n \\log n)$ with good pivot selection." },
  { question: "Best-case time complexity of Bubble sort?", options: ["$O(1)$", "$O(n)$", "$O(n \\log n)$", "$O(n^2)$"], correctIndex: 1, explanation: "Already sorted data requires exactly one pass with no swaps." },
  { question: "Worst-case time complexity of Quick sort?", options: ["$O(n)$", "$O(n \\log n)$", "$O(n^2)$", "$O(2^n)$"], correctIndex: 2, explanation: "Occurs with bad pivot choices (e.g., already sorted data)." },
  { question: "$f(n)=\\Theta(g(n))$ mathematically implies?", options: ["$f(n)=O(g(n))$ only", "$f(n)=\\Omega(g(n))$ only", "$f(n)=O(g(n))$ and $\\Omega(g(n))$", "$f(n)=o(g(n))$"], correctIndex: 2, explanation: "Theta is a tight bound, meaning it is both an upper and lower bound." }
];