export const quizData = [
  { question: "What is the worst-case space complexity of a recursive Bubble Sort implementation?", options: ["$\\mathcal{O}(1)$", "$\\mathcal{O}(\\log N)$", "$\\mathcal{O}(N)$", "$\\mathcal{O}(N^2)$"], correctIndex: 2, explanation: "Recursive Bubble Sort requires $\\mathcal{O}(N)$ auxiliary space due to the recursion call stack depth, unlike the iterative version which is $\\mathcal{O}(1)$." },
  { question: "When reading a text file line-by-line to compute the average occurrences of a string, what is the time complexity?", options: ["$\\mathcal{O}(L)$ where L is lines", "$\\mathcal{O}(L \\cdot M)$ where M is avg line length", "$\\mathcal{O}(N \\log N)$ where N is total chars", "$\\mathcal{O}(1)$"], correctIndex: 1, explanation: "You must process every line ($L$) and scan the characters within each line ($M$), resulting in $\\mathcal{O}(L \\cdot M)$ time." },
  { question: "What is the prerequisite for multiplying row $x$ of matrix $A$ with column $y$ of matrix $B$?", options: ["Rows of A == Rows of B", "Cols of A == Rows of B", "Cols of A == Cols of B", "Matrix A must be square"], correctIndex: 1, explanation: "The dot product requires the number of columns in the first operand to exactly match the number of rows in the second operand." },
  { question: "What is the time complexity of the Greedy Coin Change algorithm for a canonical system with $C$ denominations?", options: ["$\\mathcal{O}(N)$ where N is amount", "$\\mathcal{O}(C)$", "$\\mathcal{O}(C \\log C)$", "$\\mathcal{O}(2^C)$"], correctIndex: 1, explanation: "The algorithm iterates through the $C$ denominations exactly once, making it $\\mathcal{O}(C)$ time, independent of the amount." },
  { question: "In an array-based Stack, what condition triggers a Stack Overflow?", options: ["top == 0", "top == capacity", "top == capacity - 1", "size == capacity / 2"], correctIndex: 2, explanation: "If the array is 0-indexed, the last valid index is `capacity - 1`. Pushing when `top == capacity - 1` exceeds the bounds." },
  { question: "Why is Selection Sort preferred over Bubble Sort in write-heavy memory (like Flash/EEPROM)?", options: ["It has a better worst-case time", "It performs at most $\\mathcal{O}(N)$ swaps", "It uses less auxiliary space", "It is a stable sort"], correctIndex: 1, explanation: "Selection Sort makes exactly one swap per pass, resulting in at most $\\mathcal{O}(N)$ writes, whereas Bubble Sort can make $\\mathcal{O}(N^2)$ writes." },
  { question: "What data structure is fundamentally required to convert an Infix expression to Postfix?", options: ["Queue", "Stack", "Binary Tree", "Hash Map"], correctIndex: 1, explanation: "A stack is used to temporarily hold operators and enforce precedence/associativity rules while operands are output directly." },
  { question: "To find the largest value in the left subtree of a BST, which traversal path is optimal?", options: ["Go left until null", "Go left once, then right until null", "Go right until null", "Perform an in-order traversal of the whole tree"], correctIndex: 1, explanation: "The left subtree contains values smaller than the root. The maximum of that subtree is found by stepping left once, then going as far right as possible." },
  { question: "Converting a directed graph from an Adjacency List to an Adjacency Matrix takes what time complexity?", options: ["$\\mathcal{O}(V)$", "$\\mathcal{O}(V + E)$", "$\\mathcal{O}(V^2)$", "$\\mathcal{O}(E \\log V)$"], correctIndex: 2, explanation: "You must initialize a $V \\times V$ matrix with zeros ($\\mathcal{O}(V^2)$), then iterate the list to populate edges ($\\mathcal{O}(V + E)$). The dominant term is $\\mathcal{O}(V^2)$." },
  { question: "When filtering a Linked List of students to compute a GPA for only 'CSI' courses, what is the auxiliary space complexity?", options: ["$\\mathcal{O}(N)$", "$\\mathcal{O}(C)$ where C is CSI courses", "$\\mathcal{O}(1)$", "$\\mathcal{O}(\\log N)$"], correctIndex: 2, explanation: "You only need a few variables to track the running sum and count of credits/grades, resulting in $\\mathcal{O}(1)$ auxiliary space." },
  { question: "If you randomly exchange $x$ characters in a Java String, why must you convert it to a `char[]` first?", options: ["Strings are mutable", "Strings are immutable", "`char[]` is faster to iterate", "To avoid StackOverflow"], correctIndex: 1, explanation: "Java Strings are immutable. You cannot swap characters in place; you must convert to a mutable `char[]`, perform swaps, and create a new String." },
  { question: "What is the amortized time complexity of pushing to a dynamically resizing array-based Stack?", options: ["$\\mathcal{O}(1)$", "$\\mathcal{O}(\\log N)$", "$\\mathcal{O}(N)$", "$\\mathcal{O}(N^2)$"], correctIndex: 0, explanation: "While resizing takes $\\mathcal{O}(N)$, it happens so infrequently that the average cost per push over $N$ operations is $\\mathcal{O}(1)$." },
  { question: "The GPA formula $\\frac{\\sum (credit \\times grade)}{n}$ represents what type of mathematical average?", options: ["Arithmetic Mean", "Geometric Mean", "Weighted Average", "Harmonic Mean"], correctIndex: 2, explanation: "Because each grade is multiplied by its corresponding credit weight before dividing by the total credits/courses, it is a weighted average." },
  { question: "In a Post-Order traversal of a BST, when is the root node processed?", options: ["First", "Second", "Last", "When the left subtree is empty"], correctIndex: 2, explanation: "Post-Order visits Left, then Right, then Root. The root is always the final node processed in its subtree." },
  { question: "If a Greedy Coin Change algorithm is applied to a non-canonical system (e.g., coins 1, 3, 4 for target 6), what happens?", options: ["It throws an exception", "It yields the optimal result", "It yields a sub-optimal result", "It loops infinitely"], correctIndex: 2, explanation: "Greedy picks 4, then 1, then 1 (3 coins). The optimal is 3 + 3 (2 coins). Greedy fails to find the global optimum in non-canonical systems." }
];