export const quizData = [
  {
    question: "What does time complexity describe?",
    options: ["The exact seconds used on one computer", "How runtime grows as input size grows", "Only the memory used by an algorithm", "The number of lines in the source file"],
    correctIndex: 1,
    explanation: "Time complexity focuses on growth with input size rather than an exact clock time.",
  },
  {
    question: "Why should a theoretical algorithm comparison be independent of hardware?",
    options: ["Hardware never changes runtime", "The same algorithm can have different clock times on different machines", "Algorithms cannot be implemented", "Only memory affects performance"],
    correctIndex: 1,
    explanation: "Clock time varies across machines even when the algorithm is unchanged.",
  },
  {
    question: "Which is a limitation of experimental runtime testing?",
    options: ["It never uses real data", "It requires no implementation", "It tests only a limited set of inputs", "It cannot measure time"],
    correctIndex: 2,
    explanation: "An experiment may miss inputs on which the algorithm behaves differently.",
  },
  {
    question: "Which item is a primitive operation?",
    options: ["Designing an entire application", "An array-index access", "Choosing a programming language", "Buying a faster computer"],
    correctIndex: 1,
    explanation: "Array indexing is a basic, easily identifiable operation used when counting work.",
  },
  {
    question: "What does the worst case represent?",
    options: ["The shortest runtime for size N", "The expected runtime for size N", "The maximum runtime for size N", "The runtime for N = 1 only"],
    correctIndex: 2,
    explanation: "Worst-case analysis asks for the maximum work required by a valid input of size N.",
  },
  {
    question: "How do you combine the costs of sequential statements?",
    options: ["Add them", "Multiply them", "Use only the first", "Always call the result O(N)"],
    correctIndex: 0,
    explanation: "Sequential statements execute one after another, so their costs are added.",
  },
  {
    question: "For worst-case analysis of an if-else statement, which branch is used?",
    options: ["The shorter branch", "The longer-running branch", "Neither branch", "Both branches always execute"],
    correctIndex: 1,
    explanation: "Count the condition and the more expensive possible branch.",
  },
  {
    question: "A loop visits every one of N array elements once. What is its time complexity?",
    options: ["$O(1)$", "$O(log N)$", "$O(N)$", "$O(N^2)$"],
    correctIndex: 2,
    explanation: "The loop body executes N times, producing linear growth.",
  },
  {
    question: "Two nested loops each execute N times. What is the usual time complexity?",
    options: ["$O(1)$", "$O(N)$", "$O(N log N)$", "$O(N^2)$"],
    correctIndex: 3,
    explanation: "The inner statement executes N x N times.",
  },
  {
    question: "What is the Big-O complexity of $7N - 3$?",
    options: ["$O(1)$", "$O(log N)$", "$O(N)$", "$O(N^2)$"],
    correctIndex: 2,
    explanation: "The linear term dominates, and its coefficient is dropped.",
  },
  {
    question: "What is the Big-O complexity of $3N^2 + 5N$?",
    options: ["$O(N)$", "$O(N log N)$", "$O(N^2)$", "$O(N^3)$"],
    correctIndex: 2,
    explanation: "$N^2$ grows faster than $N$, so the quadratic term dominates.",
  },
  {
    question: "What is the Big-O complexity of $3 log N + 5$?",
    options: ["$O(1)$", "$O(log N)$", "$O(N)$", "$O(N log N)$"],
    correctIndex: 1,
    explanation: "Drop the coefficient and constant, leaving logarithmic growth.",
  },
  {
    question: "Which order grows more slowly as N becomes large?",
    options: ["$O(N)$", "$O(N log N)$", "$O(N^2)$", "$O(2^N)$"],
    correctIndex: 0,
    explanation: "Among these choices, linear growth is the most scalable.",
  },
  {
    question: "What is the time complexity of computing the sum of N numbers with one loop?",
    options: ["$O(1)$", "$O(log N)$", "$O(N)$", "$O(N^2)$"],
    correctIndex: 2,
    explanation: "Each of the N numbers must be processed once.",
  },
  {
    question: "Which statement about Big-O is correct?",
    options: ["It gives an exact runtime in milliseconds", "It keeps every constant in T(N)", "It focuses on the dominant growth term", "It depends on the processor model"],
    correctIndex: 2,
    explanation: "Big-O classifies growth by retaining the dominant term and ignoring constants and lower-order terms.",
  },
];
