export const quizData = [
  { question: "What is the space complexity of a standard recursive Fibonacci implementation?", options: ["O(1)", "O(log N)", "O(N)", "O(2^N)"], correctIndex: 2, explanation: "The maximum depth of the recursion tree is N, requiring O(N) space on the call stack." },
  { question: "Which algorithmic paradigm does Merge Sort use?", options: ["Backtracking", "Dynamic Programming", "Divide and Conquer", "Greedy"], correctIndex: 2, explanation: "It divides the array in half, conquers each half recursively, and merges the results." },
  { question: "What is the primary benefit of Memoization?", options: ["Reduces space complexity to O(1)", "Avoids recalculating overlapping subproblems", "Eliminates the need for a base case", "Converts recursion to iteration"], correctIndex: 1, explanation: "It caches results of expensive function calls, reducing exponential time complexities to polynomial." },
  { question: "In a backtracking algorithm, what does 'pruning' mean?", options: ["Sorting the input array", "Abandoning a branch early because it violates constraints", "Removing duplicate elements", "Converting the tree to a graph"], correctIndex: 1, explanation: "Pruning saves computation time by stopping the exploration of paths that cannot lead to a valid solution." },
  { question: "Which of the following is NOT a requirement for Dynamic Programming?", options: ["Overlapping Subproblems", "Optimal Substructure", "Greedy Choice Property", "Both A and B are requirements"], correctIndex: 2, explanation: "The Greedy Choice Property is required for Greedy Algorithms, not Dynamic Programming." },
  { question: "Time complexity to generate all permutations of a string of length N?", options: ["O(N^2)", "O(2^N)", "O(N!)", "O(N log N)"], correctIndex: 2, explanation: "There are N! possible arrangements, and processing each takes O(N) time, making it O(N * N!)." },
  { question: "What causes a StackOverflowError in recursion?", options: ["Returning the wrong data type", "Missing base case or excessively deep recursion", "Using global variables", "Passing too many arguments"], correctIndex: 1, explanation: "The call stack exceeds its allocated memory limit because the recursion never terminates." },
  { question: "Tail recursion optimization requires:", options: ["The recursive call to be the very last operation", "Using global variables", "No base case", "A return type of void"], correctIndex: 0, explanation: "Compilers can reuse the current stack frame if nothing happens after the recursive call returns." },
  { question: "Bottom-Up Tabulation typically uses which control structure?", options: ["Recursion", "Iteration (Loops)", "Queues", "Priority Queues"], correctIndex: 1, explanation: "Tabulation builds the solution iteratively from the smallest subproblems up to the final answer." },
  { question: "The recurrence relation for Merge Sort is:", options: ["T(n) = T(n-1) + 1", "T(n) = 2T(n/2) + O(n)", "T(n) = T(n/2) + O(1)", "T(n) = 2T(n-1) + O(1)"], correctIndex: 1, explanation: "It splits the problem into 2 halves (2T(n/2)) and takes O(n) time to merge them." }
];