export const quizData = [
  { question: "Master theorem: $T(n)=2T(n/2)+n$ yields?", options: ["$O(n)$", "$O(n \\log n)$", "$O(n^2)$", "$O(\\log n)$"], correctIndex: 1, explanation: "Case 2: $f(n)$ matches $n^{\\log_b a}$, resulting in $n \\log n$." },
  { question: "Time complexity of naive recursive Fibonacci?", options: ["$O(n)$", "$O(n^2)$", "$O(2^n)$", "$O(n \\log n)$"], correctIndex: 2, explanation: "The recursion tree branches exponentially." },
  { question: "Applying memoization to Fibonacci reduces time to?", options: ["$O(1)$", "$O(\\log n)$", "$O(n)$", "$O(n^2)$"], correctIndex: 2, explanation: "Each subproblem is solved exactly once." },
  { question: "Recursion tree method for $T(n)=T(n/2)+1$ yields?", options: ["$O(n)$", "$O(\\log n)$", "$O(n \\log n)$", "$O(1)$"], correctIndex: 1, explanation: "The tree has $\\log n$ levels, each doing $O(1)$ work." },
  { question: "Time complexity of the N-Queens backtracking algorithm?", options: ["$O(n^2)$", "$O(n!)$", "$O(2^n)$", "$O(n \\log n)$"], correctIndex: 1, explanation: "It explores permutations of queen placements." },
  { question: "A StackOverflowError in recursion is typically caused by?", options: ["Returning the wrong type", "Missing base case or excessively deep recursion", "Using too many variables", "Global variables"], correctIndex: 1, explanation: "The call stack exceeds its memory limit without hitting a base case." },
  { question: "Tail recursion optimization requires?", options: ["The recursive call to be the very last operation", "Using global variables", "No base case", "A return type of void"], correctIndex: 0, explanation: "Compilers can reuse the current stack frame if nothing happens after the call." },
  { question: "The Substitution Method proves bounds using?", options: ["Graph theory", "Mathematical induction", "Calculus limits", "Probability"], correctIndex: 1, explanation: "You guess the bound and prove it holds for $n$ assuming it holds for smaller values." },
  { question: "The recurrence relation for Merge Sort is?", options: ["$T(n) = T(n-1) + 1$", "$T(n) = 2T(n/2) + O(n)$", "$T(n) = T(n/2) + O(1)$", "$T(n) = 2T(n-1) + O(1)$"], correctIndex: 1, explanation: "It splits in half (2 subproblems) and takes $O(n)$ to merge." },
  { question: "Space complexity of recursive binary search?", options: ["$O(1)$", "$O(\\log n)$", "$O(n)$", "$O(n \\log n)$"], correctIndex: 1, explanation: "The call stack depth is proportional to the number of divisions." },
  { question: "Number of moves required to solve Tower of Hanoi with $n$ disks?", options: ["$n^2$", "$n!$", "$2^n - 1$", "$2n$"], correctIndex: 2, explanation: "The recurrence $T(n) = 2T(n-1) + 1$ solves to $2^n - 1$." },
  { question: "Time complexity to generate all permutations of a string of length $n$?", options: ["$O(n^2)$", "$O(2^n)$", "$O(n!)$", "$O(n \\log n)$"], correctIndex: 2, explanation: "There are $n!$ possible arrangements." },
  { question: "Dynamic Programming improves upon naive recursion by?", options: ["Using less memory", "Eliminating overlapping subproblems", "Avoiding base cases", "Using iteration instead of recursion"], correctIndex: 1, explanation: "It caches results of overlapping subproblems to avoid redundant calculations." },
  { question: "Iteration generally uses how much auxiliary memory compared to recursion?", options: ["More ($O(n)$)", "Less ($O(1)$)", "The exact same", "Iteration uses the heap"], correctIndex: 1, explanation: "Iteration uses simple variables, avoiding the call stack overhead." },
  { question: "Divide and Conquer algorithms require subproblems to be?", options: ["Overlapping", "Independent", "Identical", "Non-recursive"], correctIndex: 1, explanation: "If subproblems overlap, DP is more efficient. D&C shines when they are independent." }
];