export const quizData = [
  { question: "In a recursive Bubble Sort sorting descending between indices $x$ and $y$, what is the base case?", options: ["x == y", "x >= y", "x < y", "y == 0"], correctIndex: 1, explanation: "The recursion stops when the subarray has 1 or 0 elements, meaning it is trivially sorted. Thus, `x >= y` is the base case." },
  { question: "What is the main computational advantage of Selection Sort over Bubble Sort?", options: ["It has a better worst-case time complexity", "It performs at most $\\mathcal{O}(N)$ swaps", "It uses $\\mathcal{O}(1)$ auxiliary space", "It is a stable sorting algorithm"], correctIndex: 1, explanation: "Selection Sort makes exactly one swap per pass, resulting in at most $N$ swaps. Bubble Sort can make $\\mathcal{O}(N^2)$ swaps." },
  { question: "Using a Greedy approach for Botswana Pula change (P5, P2, P1, P0.50, P0.25, P0.10, P0.05), how many coins for P8.75?", options: ["3", "4", "5", "6"], correctIndex: 1, explanation: "P5 (1), P2 (1), P1 (1), P0.50 (1), P0.25 (1). Wait, 5+2+1+0.50+0.25 = 8.75. That is 5 coins. Let me re-verify: 8.75 / 5 = 1 (rem 3.75). 3.75 / 2 = 1 (rem 1.75). 1.75 / 1 = 1 (rem 0.75). 0.75 / 0.50 = 1 (rem 0.25). 0.25 / 0.25 = 1. Total = 5 coins." },
  { question: "Why does the Greedy Coin Change algorithm fail for denominations [1, 3, 4] with target 6?", options: ["It throws a DivisionByZero error", "It yields 3 coins (4,1,1) instead of the optimal 2 coins (3,3)", "It loops infinitely", "It requires negative coins"], correctIndex: 1, explanation: "The system is non-canonical. Greedy picks the largest possible coin (4), leaving 2, which requires two 1s. DP finds 3+3." },
  { question: "What is the time complexity of a recursive Bubble Sort?", options: ["$\\mathcal{O}(N)$", "$\\mathcal{O}(N \\log N)$", "$\\mathcal{O}(N^2)$", "$\\mathcal{O}(2^N)$"], correctIndex: 2, explanation: "Like iterative Bubble Sort, it requires $N$ passes, each doing up to $N$ comparisons, resulting in $\\mathcal{O}(N^2)$ time." },
  { question: "Which sorting algorithm is inherently unstable due to its long-distance swapping mechanism?", options: ["Bubble Sort", "Insertion Sort", "Selection Sort", "Merge Sort"], correctIndex: 2, explanation: "Selection Sort swaps the minimum element from the unsorted region directly with the boundary, easily bypassing equal elements." },
  { question: "In Binary Search, what is the correct way to calculate `mid` to prevent integer overflow?", options: ["(left + right) / 2", "left + (right - left) / 2", "right - (right - left) / 2", "(left * right) / 2"], correctIndex: 1, explanation: "`left + (right - left) / 2` prevents the sum of `left + right` from exceeding the maximum representable value for an integer." },
  { question: "What is the space complexity of Merge Sort?", options: ["$\\mathcal{O}(1)$", "$\\mathcal{O}(\\log N)$", "$\\mathcal{O}(N)$", "$\\mathcal{O}(N^2)$"], correctIndex: 2, explanation: "Merge Sort requires an auxiliary array of size $N$ to merge the sorted halves back together." },
  { question: "When is Insertion Sort the most optimal choice?", options: ["Massive, completely random datasets", "Small or nearly sorted datasets", "Datasets with many duplicates", "When memory is strictly $\\mathcal{O}(1)$"], correctIndex: 1, explanation: "Insertion Sort runs in $\\mathcal{O}(N)$ time on nearly sorted data and has very low constant overhead for small $N$." },
  { question: "What is the lower bound for any comparison-based sorting algorithm?", options: ["$\\mathcal{O}(N)$", "$\\mathcal{O}(N \\log N)$", "$\\mathcal{O}(N^2)$", "$\\mathcal{O}(\\log N)$"], correctIndex: 1, explanation: "A decision tree for $N$ elements has $N!$ leaves. The height of the tree (comparisons) must be at least $\\log_2(N!) \\approx N \\log N$." },
  { question: "How does Radix Sort achieve linear time complexity?", options: ["It uses a hash table", "It avoids comparisons by sorting digit-by-digit using a stable subroutine", "It uses a binary search tree", "It divides the array recursively"], correctIndex: 1, explanation: "By sorting individual digits (using Counting Sort) from least to most significant, it bypasses the $\\Omega(N \\log N)$ comparison limit." },
  { question: "What is the worst-case time complexity of Quick Sort?", options: ["$\\mathcal{O}(N \\log N)$", "$\\mathcal{O}(N^2)$", "$\\mathcal{O}(N)$", "$\\mathcal{O}(2^N)$"], correctIndex: 1, explanation: "Occurs when the pivot consistently partitions the array into sizes 0 and N-1 (e.g., already sorted array with first-element pivot)." },
  { question: "What does 'stable' mean in the context of sorting algorithms?", options: ["It never crashes", "It preserves the relative order of equal elements", "It uses $\\mathcal{O}(1)$ space", "It always runs in $\\mathcal{O}(N \\log N)$"], correctIndex: 1, explanation: "If two elements have the same key, their original relative order is maintained in the sorted output." },
  { question: "Which algorithm is best suited for External Sorting (data too large for RAM)?", options: ["Quick Sort", "Heap Sort", "Merge Sort", "Insertion Sort"], correctIndex: 2, explanation: "Merge Sort can sort chunks in memory and sequentially merge them from disk, making it ideal for external storage." },
  { question: "In a Greedy Coin Change algorithm, what must be done to the denominations array before processing?", options: ["Sort ascending", "Sort descending", "Randomize", "Filter out primes"], correctIndex: 1, explanation: "The greedy strategy requires checking the largest denominations first to minimize the total number of coins." }
];