export const quizData = [
  { question: "QuickSort degrades to $O(n^2)$ when?", options: ["Array is randomly ordered", "Array is already sorted and pivot is first/last element", "Array contains duplicates", "Array size is prime"], correctIndex: 1, explanation: "The partition becomes highly unbalanced (0 and n-1 elements)." },
  { question: "Space complexity of Merge Sort?", options: ["$O(1)$", "$O(\\log n)$", "$O(n)$", "$O(n^2)$"], correctIndex: 2, explanation: "It requires auxiliary arrays of size $n$ to merge the halves." },
  { question: "Space complexity of Heap Sort?", options: ["$O(1)$", "$O(\\log n)$", "$O(n)$", "$O(n \\log n)$"], correctIndex: 0, explanation: "It sorts in-place by manipulating the array as a tree." },
  { question: "Best-case time complexity of Insertion Sort?", options: ["$O(1)$", "$O(n)$", "$O(n \\log n)$", "$O(n^2)$"], correctIndex: 1, explanation: "If already sorted, the inner loop never runs." },
  { question: "Binary search strictly requires the data to be?", options: ["Stored in a linked list", "Sorted", "Integer values", "Free of duplicates"], correctIndex: 1, explanation: "It relies on dividing the search space based on comparisons." },
  { question: "Average-case time complexity of Linear Search?", options: ["$O(1)$", "$O(\\log n)$", "$O(n)$", "$O(n^2)$"], correctIndex: 2, explanation: "On average, you check half the elements, which is still $O(n)$." },
  { question: "Time complexity of Counting Sort?", options: ["$O(n \\log n)$", "$O(n^2)$", "$O(n+k)$", "$O(k \\log k)$"], correctIndex: 2, explanation: "It depends on the range of input values ($k$) plus the number of elements ($n$)." },
  { question: "Time complexity of Radix Sort?", options: ["$O(n \\log n)$", "$O(n+k)$", "$O(d(n+k))$", "$O(n^2)$"], correctIndex: 2, explanation: "It performs Counting Sort $d$ times (where $d$ is the number of digits)." },
  { question: "A sorting algorithm is 'stable' if it?", options: ["Never crashes", "Preserves the relative order of equal elements", "Uses $O(1)$ space", "Runs in $O(n \\log n)$"], correctIndex: 1, explanation: "Stability is crucial when sorting by multiple keys sequentially." },
  { question: "Which of these simple sorting algorithms is stable?", options: ["Selection Sort", "Quick Sort", "Insertion Sort", "Heap Sort"], correctIndex: 2, explanation: "Insertion sort only shifts elements strictly greater than the key." },
  { question: "Which simple sorting algorithm is inherently unstable?", options: ["Bubble Sort", "Insertion Sort", "Selection Sort", "Merge Sort"], correctIndex: 2, explanation: "The long-distance swap in Selection Sort can break the order of equal elements." },
  { question: "Average-case time complexity of Quick Sort?", options: ["$O(n)$", "$O(n \\log n)$", "$O(n^2)$", "$O(2^n)$"], correctIndex: 1, explanation: "With good pivot selection, it divides the array logarithmically." },
  { question: "An 'in-place' sorting algorithm requires how much extra space?", options: ["$O(n)$", "$O(\\log n)$", "$O(1)$", "$O(n^2)$"], correctIndex: 2, explanation: "It rearranges elements within the original array without large auxiliary structures." },
  { question: "Which algorithm is best for External Sorting (data too large for RAM)?", options: ["Quick Sort", "Heap Sort", "Merge Sort", "Insertion Sort"], correctIndex: 2, explanation: "It can sort chunks in memory and merge them from disk sequentially." },
  { question: "Interpolation search performs best on?", options: ["Linked lists", "Uniformly distributed sorted arrays", "Reverse sorted arrays", "Arrays with many duplicates"], correctIndex: 1, explanation: "It uses the value of the target to estimate its position, like looking up a name in a phonebook." }
];