export const quizData = [
  {
    question: "What is the worst-case time complexity of linear search?",
    options: ["$O(1)$", "$O(log N)$", "$O(N)$", "$O(N^2)$"],
    correctIndex: 2,
    explanation: "In the worst case, linear search checks every element before finding the target or deciding it is absent.",
  },
  {
    question: "Which condition must be true before standard binary search can be used?",
    options: ["The array must be sorted", "The array must contain no duplicates", "The array must have an even length", "The target must be present"],
    correctIndex: 0,
    explanation: "Binary search uses sorted order to decide which half of the search range can be discarded.",
  },
  {
    question: "Why is binary search $O(log N)$ in the worst case?",
    options: ["It checks every element once", "It halves the remaining search range each step", "It sorts the data while searching", "It uses two nested loops"],
    correctIndex: 1,
    explanation: "Repeated halving produces logarithmic growth.",
  },
  {
    question: "About how many comparisons does binary search need for a sorted array of 1,000,000 elements?",
    options: ["20", "1,000", "500,000", "1,000,000"],
    correctIndex: 0,
    explanation: "$2^{20}$ is just over one million, so at most about 20 halvings are needed.",
  },
  {
    question: "Why is binary search usually a poor choice for a linked list?",
    options: ["Linked lists cannot store sorted data", "Finding the middle requires traversal", "Linked lists cannot contain duplicates", "Binary search requires swaps"],
    correctIndex: 1,
    explanation: "A linked list does not provide constant-time random access to its middle element.",
  },
  {
    question: "What does one ascending Bubble Sort pass guarantee?",
    options: ["The whole array is sorted", "The smallest value moves to index 0", "The largest remaining value reaches the end of the unsorted section", "Exactly one swap occurs"],
    correctIndex: 2,
    explanation: "Adjacent swaps move the largest remaining value to the right boundary during a pass.",
  },
  {
    question: "With an early-stop flag, what is Bubble Sort's best-case time?",
    options: ["$O(1)$", "$O(log N)$", "$O(N)$", "$O(N^2)$"],
    correctIndex: 2,
    explanation: "An already sorted array needs one pass with no swaps, so the algorithm stops after $O(N)$ comparisons.",
  },
  {
    question: "Which statement best describes standard Selection Sort?",
    options: ["It repeatedly inserts a value into a sorted section", "It repeatedly selects the minimum from the unsorted section", "It compares only adjacent values", "It repeatedly halves the array"],
    correctIndex: 1,
    explanation: "Selection Sort finds the minimum remaining value and swaps it into the next sorted position.",
  },
  {
    question: "Why might Selection Sort be chosen when memory writes are expensive?",
    options: ["It is always stable", "It uses no comparisons", "It performs only $O(N)$ swaps", "Its worst case is $O(N)$"],
    correctIndex: 2,
    explanation: "Selection Sort performs at most one swap per pass even though it still performs $O(N^2)$ comparisons.",
  },
  {
    question: "What is Selection Sort's best-case time complexity?",
    options: ["$O(1)$", "$O(N)$", "$O(N log N)$", "$O(N^2)$"],
    correctIndex: 3,
    explanation: "It still scans the unsorted section on every pass, even when the data is already sorted.",
  },
  {
    question: "Which dataset is especially suitable for Insertion Sort?",
    options: ["A small, nearly sorted array", "A huge, reverse-sorted array", "An unsorted linked list requiring binary search", "Data that cannot be compared"],
    correctIndex: 0,
    explanation: "Insertion Sort has low overhead and approaches $O(N)$ when only a few elements are out of place.",
  },
  {
    question: "What happens inside Insertion Sort when the next value is smaller than values in the sorted section?",
    options: ["The array is split in half", "Larger values shift right to make a gap", "The largest value is swapped to the end", "The search stops"],
    correctIndex: 1,
    explanation: "Insertion Sort shifts larger values right, then places the selected value in the open position.",
  },
  {
    question: "What is Merge Sort's worst-case time complexity?",
    options: ["$O(N)$", "$O(N log N)$", "$O(N^2)$", "$O(2^N)$"],
    correctIndex: 1,
    explanation: "There are logarithmically many split levels, and each level merges $N$ elements.",
  },
  {
    question: "How much auxiliary space does Merge Sort usually need for an array?",
    options: ["$O(1)$", "$O(log N)$", "$O(N)$", "$O(N^2)$"],
    correctIndex: 2,
    explanation: "The merge step normally uses a temporary array that can hold the input elements.",
  },
  {
    question: "What does it mean for a sorting algorithm to be stable?",
    options: ["It always runs in $O(N log N)$", "It preserves the relative order of equal elements", "It uses $O(1)$ space", "It never uses recursion"],
    correctIndex: 1,
    explanation: "Equal-key elements appear in the same relative order after a stable sort.",
  },
];
