export const quizData = [
  { question: "Time complexity of inserting at index 0 in an ArrayList?", options: ["$O(1)$", "$O(\\log n)$", "$O(n)$", "$O(n^2)$"], correctIndex: 2, explanation: "All existing elements must be shifted one position to the right." },
  { question: "HashSet internally uses which data structure?", options: ["ArrayList", "LinkedList", "HashMap", "TreeMap"], correctIndex: 2, explanation: "It stores elements as keys in a HashMap with a dummy value." },
  { question: "Time complexity of basic operations in a TreeSet?", options: ["$O(1)$", "$O(\\log n)$", "$O(n)$", "$O(n \\log n)$"], correctIndex: 1, explanation: "It uses a Red-Black Tree, guaranteeing logarithmic time." },
  { question: "How does ConcurrentHashMap achieve thread safety in JDK 8+?", options: ["Locking the entire map", "Segment locking (JDK 7)", "CAS and synchronized on specific buckets", "Copy-on-write"], correctIndex: 2, explanation: "It locks only the specific bucket being modified, allowing high concurrency." },
  { question: "A Fail-Fast iterator throws which exception if modified?", options: ["NullPointerException", "ConcurrentModificationException", "UnsupportedOperationException", "StackOverflowError"], correctIndex: 1, explanation: "It detects structural modifications via a modCount check." },
  { question: "Setting `accessOrder=true` in LinkedHashMap is used to build?", options: ["A Thread-Safe Map", "An LRU Cache", "A Sorted Map", "A Bloom Filter"], correctIndex: 1, explanation: "It moves accessed entries to the end, making the eldest entry the least recently used." },
  { question: "CopyOnWriteArrayList is best suited for?", options: ["High write, low read", "High read, low write", "Frequent sorting", "Null-heavy data"], correctIndex: 1, explanation: "Writes are expensive (copying the array), but reads are fast and thread-safe." },
  { question: "The default ordering of a Java PriorityQueue is?", options: ["Max-Heap", "Min-Heap (Natural Ordering)", "FIFO", "LIFO"], correctIndex: 1, explanation: "The head is the least element according to natural ordering." },
  { question: "Keys in a TreeMap must implement?", options: ["Serializable", "Comparable (or provide a Comparator)", "Cloneable", "Iterable"], correctIndex: 1, explanation: "It needs to know how to sort the keys to maintain the Red-Black tree." },
  { question: "What is the default initial capacity of an ArrayList?", options: ["0", "10", "16", "32"], correctIndex: 1, explanation: "It starts at 10 and grows by 50% (oldCapacity + (oldCapacity >> 1)) when full." },
  { question: "The default load factor of a HashMap is?", options: ["0.5", "0.75", "0.9", "1.0"], correctIndex: 1, explanation: "It resizes when 75% full to balance time and space complexity." },
  { question: "Primary difference between Vector and ArrayList?", options: ["Vector is faster", "Vector is synchronized (thread-safe)", "Vector allows nulls, ArrayList doesn't", "Vector is immutable"], correctIndex: 1, explanation: "Vector's methods are synchronized, making it slower but thread-safe." },
  { question: "Collections.unmodifiableList() returns?", options: ["A deep copy of the list", "A read-only view of the original list", "A new synchronized list", "An empty list"], correctIndex: 1, explanation: "It wraps the original list; attempts to modify it throw UnsupportedOperationException." },
  { question: "Best Queue implementation for BFS?", options: ["PriorityQueue", "ArrayDeque", "Stack", "Vector"], correctIndex: 1, explanation: "ArrayDeque is faster and more memory-efficient than LinkedList for queues." },
  { question: "How many null elements can a HashSet store?", options: ["0", "1", "Unlimited", "Depends on capacity"], correctIndex: 1, explanation: "It allows exactly one null element (hashes to bucket 0)." }
];