export const quizData = [
  { question: "In Java, local primitive variables are stored in which memory area?", options: ["Heap", "Stack", "Method Area", "Native Memory"], correctIndex: 1, explanation: "Primitives and object references live on the call stack for fast access." },
  { question: "Method overloading is an example of which type of polymorphism?", options: ["Runtime", "Compile-time", "Dynamic", "Encapsulation"], correctIndex: 1, explanation: "The compiler resolves which method to call based on parameter types." },
  { question: "Which Java version introduced default methods in interfaces?", options: ["Java 5", "Java 7", "Java 8", "Java 11"], correctIndex: 2, explanation: "Java 8 allowed interfaces to have method implementations to support lambdas." },
  { question: "In the PECS principle, `? super Integer` means?", options: ["Read-only (Producer)", "Write-only (Consumer)", "Read/Write", "Immutable"], correctIndex: 1, explanation: "Super allows adding Integers or their subclasses, but you can only read Objects." },
  { question: "The Garbage Collector triggers when?", options: ["The programmer calls free()", "An object has zero references", "The stack overflows", "Every 1000 operations"], correctIndex: 1, explanation: "Java uses automatic garbage collection based on reachability." },
  { question: "Because Strings are immutable, calling `concat()` does what?", options: ["Modifies the original string", "Creates and returns a new String object", "Throws an exception", "Returns null"], correctIndex: 1, explanation: "Immutability means any modification results in a completely new object." },
  { question: "Which access modifier is the most restrictive?", options: ["public", "protected", "default", "private"], correctIndex: 3, explanation: "Private restricts access to only within the same class." },
  { question: "A `static` method can directly access?", options: ["Instance variables", "Only other static members", "The `this` keyword", "Non-static methods"], correctIndex: 1, explanation: "Static methods belong to the class, not an instance, so they lack `this`." },
  { question: "Generic type erasure occurs at which phase?", options: ["Runtime", "Compile-time", "Execution", "Garbage Collection"], correctIndex: 1, explanation: "The compiler removes generic types to maintain backward compatibility." },
  { question: "What is the difference between `==` and `.equals()` for Strings?", options: ["They are identical", "`==` checks value, `.equals()` checks reference", "`==` checks reference, `.equals()` checks value", "Neither works on Strings"], correctIndex: 2, explanation: "`==` checks if they point to the exact same memory address." },
  { question: "Java Wrapper classes (like Integer) are?", options: ["Mutable", "Immutable", "Abstract", "Serializable only"], correctIndex: 1, explanation: "Once created, their internal value cannot be changed." },
  { question: "A `finally` block will execute even if there is?", options: ["A `return` statement in the try block", "A `System.exit(0)` call", "A power failure", "A syntax error"], correctIndex: 0, explanation: "`finally` runs after try/catch, even if a value is returned. (Except System.exit)." },
  { question: "Which of the following is a Marker Interface?", options: ["Comparable", "Iterable", "Serializable", "Runnable"], correctIndex: 2, explanation: "It has no methods; it just signals the compiler/JVM to add special behavior." },
  { question: "The `volatile` keyword ensures?", options: ["Atomicity of compound operations", "Visibility of changes across threads", "Immutability", "Thread safety for all operations"], correctIndex: 1, explanation: "It forces threads to read the variable from main memory, not CPU cache." },
  { question: "The `transient` keyword does what?", options: ["Makes a variable thread-safe", "Excludes a variable from serialization", "Makes a variable constant", "Deletes the variable after use"], correctIndex: 1, explanation: "Transient variables are skipped when the object is converted to a byte stream." }
];