export const flashcardData = [
  { front: "JVM", back: "The Java Virtual Machine executes compiled Java bytecode, allowing the same program to run on different platforms with a compatible JVM." },
  { front: "Java compilation flow", back: "Source code in a .java file is compiled into bytecode in a .class file, which is then executed by the JVM." },
  { front: "Primitive type", back: "A built-in value type such as int, double, boolean, or char." },
  { front: "Strong typing", back: "Variables have declared types, and Java checks that assigned and returned values are type-compatible." },
  { front: "Widening conversion", back: "An automatic conversion to a type with a broader range, such as int to double." },
  { front: "Narrowing conversion", back: "An explicit cast to a smaller or less precise type, such as double to int, which may lose information." },
  { front: "Integer division", back: "When both operands are integers, Java discards the fractional part of the quotient before any later conversion." },
  { front: "Variable scope", back: "The region of code in which a variable can be accessed, usually bounded by the braces of its declaring block." },
  { front: "String ==", back: "Tests whether two references point to the same object; it does not normally test whether their text is equal." },
  { front: "String .equals()", back: "Compares the character content of strings." },
  { front: "One-line if statement", back: "Without braces, only the next statement is controlled by the if; indentation does not affect Java syntax." },
  { front: "Array", back: "A fixed-length object holding values of one declared type." },
  { front: "First array index", back: "Index 0." },
  { front: "Last array index", back: "length - 1." },
  { front: "for loop", back: "Best suited to count-controlled repetition, especially when the number of iterations is known." },
  { front: "while loop", back: "Tests its condition before every iteration and may execute zero times." },
  { front: "do-while loop", back: "Tests its condition after the body, guaranteeing at least one execution." },
  { front: "Scanner next()", back: "Reads one token and stops at whitespace." },
  { front: "Scanner nextLine()", back: "Reads the remainder of the current line, including spaces, up to the line ending." },
  { front: "Scanner nextInt() pitfall", back: "It leaves the line ending behind, so a later nextLine() may consume that empty remainder immediately." },
  { front: "hasNextInt()", back: "Checks whether the next input token can be interpreted as an integer without consuming it." },
  { front: "try-catch", back: "Runs risky code in try and handles matching exceptions in catch so the program can respond instead of terminating unexpectedly." },
  { front: "Method", back: "A named, reusable block of code that can accept parameters and optionally return a value." },
  { front: "void method", back: "A method that performs an action but does not return a value." },
  { front: "Return type", back: "The declared type of value a method promises to send back to its caller." },
  { front: "Parameter", back: "A variable declared in a method definition to receive input." },
  { front: "Argument", back: "The actual value or expression supplied in a method call." },
  { front: "File persistence", back: "Files retain data after a program stops, unlike ordinary variables held only in memory." },
  { front: "IOException", back: "An exception representing a failure during an input or output operation." },
  { front: "try-with-resources", back: "A try form that automatically closes resources such as readers, writers, and scanners." },
];
