export type LessonGuide = { objectives: string[]; prerequisites: string[] };

export const LESSON_GUIDES: Record<string, LessonGuide> = {
  foundations: { objectives: ["Interpret indefinite and definite integrals", "Apply the basic antiderivative rules", "Use both parts of the Fundamental Theorem of Calculus"], prerequisites: ["Derivative rules", "Function notation", "Signed area and interval notation"] },
  substitution: { objectives: ["Recognise a reverse-chain-rule pattern", "Transform an integral completely into u", "Handle constants, leftover terms, and definite bounds correctly"], prerequisites: ["Chain rule", "Basic antiderivatives", "Algebraic rearrangement"] },
  partials: { objectives: ["Classify denominator factors", "Build and solve the correct decomposition", "Integrate every resulting term"], prerequisites: ["Polynomial factorisation and division", "Solving simultaneous equations", "Logarithmic and arctangent antiderivatives"] },
  parts: { objectives: ["Recognise products suited to integration by parts", "Choose u with LIATE", "Handle repeated, cyclic, and definite applications"], prerequisites: ["Product rule", "Basic antiderivatives", "Substitution"] },
  "reduction-formulas": { objectives: ["Derive a recurrence by integration by parts", "State its valid range and base cases", "Reduce a requested member without losing boundary terms"], prerequisites: ["Integration by parts", "Recurrence notation", "Trigonometric identities"] },
  trig: { objectives: ["Choose identities from the parity of the powers", "Integrate sine-cosine and secant-tangent products", "Use product-to-sum for different angles"], prerequisites: ["Pythagorean identities", "Double-angle identities", "Substitution"] },
  "trig-substitution": { objectives: ["Match each quadratic radical to the correct substitution", "Simplify with a Pythagorean identity", "Return to x with a reference triangle"], prerequisites: ["Trigonometric identities", "Inverse trigonometric functions", "Substitution"] },
  weierstrass: { objectives: ["Convert rational trigonometric expressions into rational functions", "Complete the resulting algebraic integral", "Decide when a shorter method is available"], prerequisites: ["Half-angle identities", "Rational integration", "Partial fractions"] },
  improper: { objectives: ["Identify every source of impropriety", "Replace it with the correct one-sided limit", "Decide convergence before reporting a value"], prerequisites: ["Limits", "Definite integration", "p-integrals"] },
  numerical: { objectives: ["Construct Riemann, trapezoidal, and Simpson approximations", "Apply the correct weight pattern", "Predict and estimate error"], prerequisites: ["Function tables", "Sigma notation", "Concavity and derivatives"] },
  applications: { objectives: ["Translate geometry into a representative slice", "Select disks, washers, shells, or length formulas", "Check units and geometric reasonableness"], prerequisites: ["Definite integration", "Graph intersections", "Plane and solid geometry"] },
  lhopital: { objectives: ["Classify an indeterminate form", "Apply L'Hopital only when its conditions hold", "Transform products, differences, and powers before differentiating"], prerequisites: ["Limits", "Derivative rules", "Logarithm laws"] },
  "sequences-series": { objectives: ["Distinguish sequence limits from series convergence", "Select and justify a convergence test", "Classify absolute versus conditional convergence"], prerequisites: ["Limits", "Geometric series", "Inequalities and improper integrals"] },
  "power-series": { objectives: ["Find radius and interval of convergence", "Test endpoints separately", "Differentiate and integrate a power series inside its radius"], prerequisites: ["Series convergence tests", "Factorials", "Interval notation"] },
  taylor: { objectives: ["Construct Taylor and Maclaurin polynomials", "Use known series to build new ones", "Bound approximation error with the Lagrange remainder"], prerequisites: ["Repeated derivatives", "Power series", "Factorials and function bounds"] }
};
